### ISSUE TITLE
OFFSET 관련 문의

### ISSUE THREAD

**Issue by Myeongjoon** [netcrazy/elasticsearch-jaso-analyzer#10]
안녕하십니까.
해당 오픈소스를 사용하려고 생각중입니다.
그러던중 사소한 버그 등을 발견 해서 문의드립니다.
es상에서 검색한 토큰의 위치를 가르키는 offset의 기능이 있는데요. 이는 토큰의 시작과 끝을 가르키는 기능입니다.
highlight 기능을 사용하게 되면 해당 토큰이 있는 위치에 <em>태그를 추가해서 리턴해주는데요.
jaso 플러그인의 동작 방식이 한영 변환, 자소 변환 등의 토큰도 추가해서 동작하며, 두개의 추가된 토큰도 offset에 영향을 주는듯 합니다.
예를 들어서 `hello`라는 데이터가 들어갔을 경우 `hello` , `ㅗ디ㅣㅐ` 두개의 토큰이 생성되어 offset에도 영향을 주고 있습니다. 
혹시 이에 대하여 제가 버그를 수정해봐도 될지 문의 드립니다.

**Comment by netcrazy** [comment]
네 안녕하세요.
hello로 색인할때 두개의 토큰 "hello , ㅗ디ㅣㅐ"이 생성되는것은 의도된 기능입니다. 한영변환 오타검색일때도 노출될수 있게 토큰을 추가한것입니다
다음과 같이 mistype을 false로 변경하면 오타 토큰이 생성되지 않습니다.

"jaso_index_tokenizer": {
            "type": "jaso_tokenizer",
            "mistype": fase,
            "chosung": true
          }
