### ISSUE TITLE
포함하는 단어

### ISSUE THREAD

**Issue by H4R1B0** [netcrazy/elasticsearch-jaso-analyzer#20]
현재 데이터가
사과, 바나나사과, 사과바나나 이렇게 저장되어있으면
사과로 검색하는 경우 사과랑 사과바나나가 이렇게 뜹니다.

시작하는 단어가 아닌 포함하는 단어도 출력하는 싶은 경우 어느 부분을 수정해야할까요

**Comment by netcrazy** [comment]
색인전에 "바나나사과"를 "바나나 사과" 로 nori를 활용해서 분리해 elasticsearch-jaso-analyzer 로 색인하면 현재 버전으로도 포함하는 단어를검색할수 있을것 같습니다.

**Comment by H4R1B0** [comment]
> 색인전에 "바나나사과"를 "바나나 사과" 로 nori를 활용해서 분리해 elasticsearch-jaso-analyzer 로 색인하면 현재 버전으로도 포함하는 단어를검색할수 있을것 같습니다.

답변 감사합니다.
nori로 먼저 분리하고 색인하려고하는데 둘다 tokenizer인데 이걸 어떻게 같이 사용해야할지 모르겠는데 답변 가능할까요

**Comment by netcrazy** [comment]
네, 맞습니다. jaso 분해가 tokenizer로 개발되어있어, 분명히 한계가 있습니다.
색인 어플리케이션에서 nori로 분해해서 인덱싱이 진행되어야 합니다.

**Comment by H4R1B0** [comment]
> 네, 맞습니다. jaso 분해가 tokenizer로 개발되어있어, 분명히 한계가 있습니다. 색인 어플리케이션에서 nori로 분해해서 �인덱싱이 진행되어야 합니다.

아하! 그러면 자바에서 nori로 분리하고 인덱싱을 해야겠군요..
그럼 더 찾아보겠습니다!! 감사합니다!!!
