### ISSUE TITLE
오픈 소스 라이센스 명시해 주시면 좋겠네요.

### ISSUE THREAD

**Issue by skyer9** [netcrazy/elasticsearch-jaso-analyzer#6]
소스를 오픈했다고 오픈소스가 되는것이 아니라
명시적으로 이 소스는 오픈소스임을 명시해야만 오픈소스가 되요.

라이센스 명시가 없으면
소스를 공개해도 여전히 개인 소스가 되어서요.

MIT 나 Apache 같은 라이센스 명시해주시면 좋을 듯 해요.

**Comment by netcrazy** [comment]
네 ^^; 라이센스 추가했습니다.
조언 감사드립니다.
