### ISSUE TITLE
써보니까 무지 좋네요

### ISSUE THREAD

**Issue by skyer9** [netcrazy/elasticsearch-jaso-analyzer#8]
네이버 자동완성 부럽지 않은 기능이네요.

[제 블로그](https://www.skyer9.pe.kr/wordpress/?p=1101) 에 기능 구현해서 올려봤는데...
자모 단위 자동완성, 한영자판오류에 대해서도 검색이 되고...
정말 좋네요.

**Comment by netcrazy** [comment]
도움이 되셨다니 저도 기분이 좋네요. 감사합니다!!

**Comment by skyer9** [comment]
저도 감사합니다 ㅎㅎ
